[[redirects]]
from = "abc"
status = 878
to = "sdfsaf"

[[redirects]]
from = "www.google.com"
status = 10
to = "/a"

[[redirects]]
from = "/old-path"
status = 301
to = "/new-path"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[build]
publish = "public"
command = "npm run build"
functions = "lambda"

[build.environment]
NODE_VERSION = "12"
YARN_VERSION = "1.22.4"
YARN_FLAGS = "--no-ignore-optional"
