[[redirects]]
from = "nothing special"
status = 404
to = "repository"

[[redirects]]
from = "12"
status = 404
to = "repository"

[[redirects]]
from = "no"
status = 878
to = "sdfsaf"

[[redirects]]
from = "well"
status = 22
to = "repository"

[[redirects]]
from = "how"
status = 10
to = "/a"

[[redirects]]
from = "/old-path"
status = 301
to = "/new-path"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[build]
publish = "public"
command = "npm run build"
functions = "lambda"

[build.environment]
NODE_VERSION = "12"
YARN_VERSION = "1.22.4"
YARN_FLAGS = "--no-ignore-optional"
