[[redirects]]
from = "/old-path"
status = 301
to = "/new-path"

[[redirects]]
from = "sdsafsf"
status = 999
to = "dasdfasdf"

[[redirects]]
from = "newkhan"
status = 897
to = "Holdone"

[[redirects]]
from = "Faisa"
status = 33
to = "SADf"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[build]
publish = "public"
command = "npm run build"
functions = "lambda"

[build.environment]
NODE_VERSION = "12"
YARN_VERSION = "1.22.4"
YARN_FLAGS = "--no-ignore-optional"
